<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="Elastic.Clients.Elasticsearch" Version="9.3.4" />
    <PackageVersion Include="FluentAssertions" Version="7.0.0-alpha.3" />
    <PackageVersion Include="FluentResults" Version="3.15.2" />
    <PackageVersion Include="FluentResults.Extensions.FluentAssertions" Version="2.1.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="NSubstitute" Version="5.1.0" />
    <PackageVersion Include="Lifti.Core" Version="7.0.2" />
    <PackageVersion Include="Testcontainers" Version="4.11.0" />
    <PackageVersion Include="Testcontainers.Elasticsearch" Version="4.11.0" />
    <PackageVersion Include="xunit" Version="2.5.3" />
    <PackageVersion Include="Xunit.DependencyInjection" Version="9.3.0" />
    <PackageVersion Include="Xunit.DependencyInjection.AspNetCoreTesting" Version="9.0.0" />
    <PackageVersion Include="Xunit.DependencyInjection.Logging" Version="9.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
</Project>